In [1]:
# Table of Contents

# 01. Data Preprocessing
# 02. Decision Trees
# 03. Visualizing Trees

In [1]:
# 01. Data Preprocessing

# To utilize decision trees, we need to prepare a numerical feature space
# Advanced decision trees, e.g., C4.5, can automatically split numerical features into nominal groups

import pandas as pd
from sklearn import preprocessing
from IPython.display import display, HTML

df=pd.read_csv('data_students_10k.csv')
print(df.shape)
# strip column names
df=df.rename(columns=lambda x: x.strip())
cols=df.columns
# print out and display dataframe as tables in HTML
display(HTML(df.head(10).to_html()))
df_raw=df.copy(deep=True)

# replace missing values in numerical variables by using mean value #################################
df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Hours on Assignments"].fillna(df["Hours on Assignments"].mean(), inplace=True)
df["Hours on Games"].fillna(df["Hours on Games"].mean(), inplace=True)
df["Exam"].fillna(df["Exam"].mean(), inplace=True)
df["Grade"].fillna(df["Grade"].mean(), inplace=True)

# check again whether there are missing values
print('ColumnName, DataType, MissingValues')
for i in cols:
    print(i, ',', df[i].dtype,',',df[i].isnull().any())
 
# remove column ID and grade which are not appropriate to be included in this classification task
df=df.drop('ID',1)
df=df.drop('Grade',1)

# encode labels
y = df['GradeLetter'] # define label as nominal values
le = preprocessing.LabelEncoder()
le.fit(y)
y_encoded = le.transform(y) # encode nominal labels to integers #####################################
df['GradeLetter'] = y_encoded

# print out and display dataframe as tables in HTML
display(HTML(df.head(10).to_html()))

# Data preprocessing ################################################################################
print('Column Datatypes:\n',df.dtypes)

# convert all nominal variables to binary variables
df_num=df.copy(deep=True) 
# create new binary columns
df_dummies=pd.get_dummies(df_num[['Degree','Nationality']])
# add them to dataframe
df_num=df_num.join(df_dummies)
# drop original columns
df_num=df_num.drop('Degree',axis=1)
df_num=df_num.drop('Nationality', axis=1)

# drop extra binary columns, since we only need N-1 binary columns
df_num=df_num.drop('Degree_ BS', axis=1)
df_num=df_num.drop('Nationality_ China', axis=1)

display('df_num:',HTML(df_num.head(10).to_html()))

(10000, 12)

ColumnName, DataType, MissingValues
ID , int64 , False
Nationality , object , False
Gender , int64 , False
Age , int64 , False
Degree , object , False
Hours on Readings , int64 , False
Hours on Assignments , int64 , False
Hours on Games , int64 , False
Hours on Internet , int64 , False
Exam , float64 , False
Grade , float64 , False
GradeLetter , object , False

C:\Users\Yong\AppData\Local\Temp\ipykernel_32312\941065492.py:32: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df=df.drop('ID',1)
C:\Users\Yong\AppData\Local\Temp\ipykernel_32312\941065492.py:33: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df=df.drop('Grade',1)

Column Datatypes:
 Nationality              object
Gender                    int64
Age                       int64
Degree                   object
Hours on Readings         int64
Hours on Assignments      int64
Hours on Games            int64
Hours on Internet         int64
Exam                    float64
GradeLetter               int32
dtype: object

'df_num:'

In [2]:
# 02. Decision Trees

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_validate, cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score

# API for DecisionTreeClassifier
# https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier

y = df_num['GradeLetter']
x = df_num.drop('GradeLetter', axis=1)

# by hold-out evaluation
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
clf=DecisionTreeClassifier(criterion='entropy', max_depth=10, ccp_alpha = 0.1) # note: there are many parameters in API
clf=clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
acc=accuracy_score(y_test, y_pred)
pre=precision_score(y_test, y_pred, average='macro')
rec=recall_score(y_test, y_pred, average='macro')
print('By hold-out evaluation: accuracy = ',acc, ', precison = ', pre, ', recall = ', rec)

# by N-fold cross validation
clf=DecisionTreeClassifier(criterion='entropy', max_depth=10, ccp_alpha = 0.1)
precision = make_scorer(precision_score, average='macro')
recall = make_scorer(recall_score, average='macro')
acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
pre=cross_val_score(clf, x, y, cv=5, scoring=precision).mean()
rec=cross_val_score(clf, x, y, cv=5, scoring=recall).mean()
print('By N-fold Cross Validation: accuracy = ',acc, ', precison = ', pre, ', recall = ', rec)

C:\Users\Yong\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

By hold-out evaluation: accuracy =  0.6013333333333334 , precison =  0.49066325875431305 , recall =  0.47551683424455293

C:\Users\Yong\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Yong\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Yong\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Yong\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Yong\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

By N-fold Cross Validation: accuracy =  0.6035 , precison =  0.4709308350143817 , recall =  0.4867494804479045

In [5]:
# 03. Visualizing decision trees
# You need to run "conda install -c anaconda python-graphviz" in Mac Terminal or Windows Anaconda Prompt
from sklearn import tree
import graphviz

clf=DecisionTreeClassifier(criterion='entropy', max_depth=100, ccp_alpha = 0.1)
rst = cross_validate(clf, x, y, cv=5, scoring='accuracy', return_estimator=True)
# get fitted trees for each fold
trees = rst['estimator']
# print accuracy scores for each fold
scores = rst['test_score']
print(scores)

# select the best model
clf = trees[2]

# encode labels
labels = le.inverse_transform([0,1,2,3])

print('features: ', x.columns.to_list())
print('labels: ', labels)

# DOT data
dot_data = tree.export_graphviz(clf, out_file=None, 
                                feature_names=x.columns.to_list(),  
                                class_names=labels,
                                filled=True)

# Draw graph
graph = graphviz.Source(dot_data, format="png") 
# save graph to MyDecisionTree.png
graph.render("MyDecisionTree")
graph

[0.5945 0.6015 0.6305 0.604  0.587 ]
features:  ['Gender', 'Age', 'Hours on Readings', 'Hours on Assignments', 'Hours on Games', 'Hours on Internet', 'Exam', 'Degree_ MS', 'Degree_ PHD', 'Nationality_ France', 'Nationality_ India', 'Nationality_ Spain']
labels:  ['A' 'B' 'C' 'F']

In [16]:
# In-Class Practice: using the Loans data for practice and assignments